# -*- coding: utf-8 -*-
"""Лабораторная№3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zTgcdQXURx1Wjrp-s_8aGpy5gEFOgWvn
"""

language="english"
if language=="english":
  print("Hello")
print("End")

language="english"
if language=="english":
  print("Hello")
  print("End")

language="russian"
if language=="english":
  print(Hello)
else:
  print("Привет")
print("End")

language="russian"
if language=="english":
  print(Hello)
  print(World)
else:
  print("Привет")
  print("Мир")

language="german"
if language=="english":
  print("Hello")
  print("World")
elif language=="german":
  print("Hello")
  print("Welt")
else:
  print("Привет")
  print("мир")

language = "english"
daytime=="morning"
if language=="english":
   print("English")
   if daytime=="morning":
     print("Good morning")
   else:
     print("Good morning")

language = "english"
daytime = "morning"
if language == "english":
    print("English")
if daytime == "morning":
    print("Good morning")
else:
     print("Good evening")

language = "russian"
daytime = "morning"
if language == "english":
    if daytime == "morning":
        print("Good morning")
    else:
        print("Good evening")
else:
    if daytime == "morning":
        print("Доброе утро")
    else:
        print("Добрый вечер")

"""Задания для самостоятельного выполнения:

1.
"""

month=int(input())
if month==1:
  print("Январь")
if month==2:
  print("Февраль")
if month==3:
  print("Март")
if month==4:
  print("Апрель")
if month==5:
  print("Май")
if month==6:
  print("Июнь")
if month==7:
  print("Июль")
if month==8:
  print("Август")
if month==9:
  print("Сентябрь")
if month==10:
  print("Октябрь")
if month==11:
  print("Ноябрь")
if month==12:
  print("Декабрь")

"""2."""

x=int(input())
if not x % 2:
  print("чётное")
else:
  print("нечётное")

"""3."""

N=int(input())
if N>40:
  print("stonks")
else:
  print("not stonks")

"""4."""

def is_year_leap():
 year = int(input("Введите год"))
 if year % 4 == 0 or (year % 100 != 0 and year % 400 == 0):
   return True
 else:
   return False
is_year_leap()

"""5."""

def  is_prime():
  n=int(input())
  for i in range(2,n):
    if n%i==0:
      return False
    else:
      return True
is_prime()

"""6."""

import math
a=float(input())
b=float(input())
n = (-138/2)**1.3
m = abs((-69/28**5.1)*4)
nr = n.real
ni = n.imag
na = -1*(nr**2+ni**2)**(0.5)
if (a>=3.6*b) or (b>=na and b>=(m)):
  a,b = b,a
print(a,b)

"""7."""

a=int(input())
b=int(input())
c=int(input())
d=int(input())
e=int(input())
k=0
s=0
g=0
if a!=b!=c!=d!=e:
  print(True)
if a%2==0:
  k += 1
if b%2==0:
  k += 1
if c%2==0:
  k += 1
if d%2==0:
  k += 1
if e%2==0:
  k += 1
print(k)
if a<0:
  s += 1
if b<0:
  s += 1
if c<0:
  s += 1
if d<0:
  s += 1
if e<0:
  s += 1
print(s)
if a in range(-256 , 1024):
  g += 1
if b in range(-256 , 1024):
  g += 1
if c in range(-256 , 1024):
  g += 1
if d in range(-256 , 1024):
  g += 1
if e in range(-256 , 1024):
  g += 1
print(g)

arr = []
a=float(input())
arr.append(a)
b=float(input())
arr.append(b)
c=float(input())
arr.append(c)
d=float(input())
arr.append(d)
e=float(input())
arr.append(e)
kc = 0
knc = 0
kot = 0
kpr = 0
for el in arr:
  if not el%2:
    kc+=1
  else:
    knc+=1
  
  if el<0:
    kot+=1
  if el>-256 and el<1024:
    kpr+=1
sarr = set(arr)
if len(sarr) != len(arr):
  print("Есть повторы")
else:
  print("Нет повторов")
print(f'Кол-во чётных = {kc}')
print(f'Кол-во нечётных = {knc}')
print(f'Кол-во отрицательных = {kot}')
print(f'Кол-во чисел в промежутке [-256; 1024] = {kpr}')

import math
a = float(input())
b = float(input())
c = float(input())
res = 0
a2 = a**2
b3 = b**3
if c==-3:
  res = math.inf
else:
  res = ((a2+b3)/(c+3))/4
print(f'Ответ: {res}')